cc_library(
        name = "ilang",
        srcs = glob(["ilang/*.cc"]),
        hdrs = glob(["ilang/*.h"]),
        deps = [
                "//kernel:kernel"
        ],
        visibility = ["//visibility:public"],
)
